Messaging
software-students-fall2021/project-setup-eventedge pull request #102
Opened 2021-11-03 07:02 UTC by ioshir4350

I have added styling, so that self messages are on the right and other messages are on the left. Right now, I have commented out the local authentication we had, so for testing purposes, you can log in with any credentials. Messaging has been completed for the most part - socket.io is taking care of live messaging. One blocker though is once someone leaves a chat and goes to a new one, the previous chat's new messages will arrive in the current chat. However, the backend still appropriately saves it to the messages corresponding chat. (Local array is just being used to save chat messages for the time being.) Therefore, when you reload, the correct messages appear, and the socket also joins the current chat's room. 
Some solutions:
- Figure out how to incorporate that reload when opening up the chat (should already be working though because of useEffect, but isn't for some reason - as long as user doesn't notice reload, solution is alright)
- Pass the chatId along with the message from the backend and check if the message being received in the front-end matches the id of the chat (simple, but very inefficient)
- Make the socket leave the room as soon as the user goes to a different page, and connect to a different room when a different chat is selected (ideal solution).

2021-11-03 21:21 UTC, nedjulius requested changes
Some comments regarding code style. Otherwise it's nice, and it's working, good job 👍

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/app/app.jsx
> +                <Chats socket={socket} />
Why are you passing `socket` object to Chats component? I think it's enough to have it in the `Chat` component, as it is not reused in the `Chats` list

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chats/chats.jsx
> +  // const {isLoading, isError, data} = useChatService.useChats();
we should be fetching chats from the backend. please revert changes in this file, because currently they do not represent the actual implementation.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/login/login.jsx
> +  // const username = 'test';
please remove stale code: do not leave commented out code, you can always check it back in the git history if you need to retrieve it!

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/login/login.jsx
> +      // if (info.username === username && info.password === password) {
please remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/send-message/send-message.jsx
> +export const SendMessage = (props) => {
always explicitly expand props; do not use props object as a whole. for example, if your `props` object has properties like `chatId`, `hi` you should expand them in the arguments like that: `SendMessage = ({chatId, hi}) => ...`

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/send-message/send-message.jsx
> +export const SendMessage = (props) => {
this helps to understand what props need to be passed and etc.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/send-message/send-message.jsx
> +  const [msg, setMsg] = useState('');
why use `msg`? `message` would be much clearer IMO

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +  // const mapChatMessages = isLoading ? (
please remove stale code

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +    const text =
you don't really need this `const`; you can instead return all of its contents implicitly: `(obj) => (...)`

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +  // if (isError) {
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +        {/* <p>Here: {response}</p> */}
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +      // console.log(data);
remove stale code

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +  const testDataHandler = (msgObj) => {
do you intend to leave it name `testDataHandler`? as I see, it's not really testing anything (?)

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +  // console.log(chatId);
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +  // const [response, setResponse] = useState('');
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +  // const {isLoading, isError, data} = useChatService.useChatMessages(chatId);
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +// import socketIOClient from 'socket.io-client';
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +// import {useChatService} from '../../lib/services/chat-service';
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on back-end/app.js
> +    // const join = username + " read"
remove stale code.

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +export const Chat = (props) => {
please expand props to make it clear what props are used in the component

2021-11-03 21:21 UTC, nedjulius commented on front-end/src/components/chat/chat.jsx
> +    // if (testData[0] === null){}
remove stale code.

2021-11-04 23:54 UTC, ioshir4350 commented on front-end/src/components/app/app.jsx
> +                <Chats socket={socket} />
So the reason for that was because I wanted to create one client socket once the app is opened. That socket would then join different "rooms" depending on which chat is entered. This would be the approach that I would vouch for. But considering that the rooms aren't switching without a reload after entering the chat, we might have to go with the approach you're suggesting. We would create a new socket to the backend every time a chat is opened.

2021-11-04 23:56 UTC, ioshir4350 commented on front-end/src/components/chats/chats.jsx
> +  // const {isLoading, isError, data} = useChatService.useChats();
I did this because mockaroo wasn't working anymore for some reason.

2021-11-06 19:14 UTC, nedjulius approved these changes

2021-11-06 19:14 UTC, merged