Farhan sprint4
software-students-fall2021/project-setup-eventedge pull request #149
Opened 2021-11-14 00:13 UTC by fm1539

2021-11-14 16:49 UTC, nedjulius requested changes

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +const getAllEventsInChat = async (req, res) => {
we don't really need this controller; we don't have a route for it. also you changed names of controllers, but didn't update the router. always run `npm run lint` before making a pull request.

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +const acceptPending = (req, res) => { //assuming events array in user schema contains both pending and accepted
we should change design of `Event` model. now, if one user accepts the pending event, it's going to be accepted for all other users who are part of that event. same goes for declined.

we should remove `isPending` field from `Event` model and modify `User` model to contain fields `pendingEvents` instead of `events` and `acceptedEvents`. When user accepts an event, it's id should be deleted from the `pendingEvents` array and added to `acceptedEvents`. The `Event` model should remain unchanged.

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +  Users.findOne({username: req.body.username}, (err, foundUser) => {
also, it's not `Users` but `User`. please run `npm run lint`

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +          Events.findOne({id: req.body.eventId}, (err, foundEvent) => {
not `Events` but `Event`

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +const declinePending = (req, res) => { //assuming events array in user schema contains both pending and accepted
Same logic mistake regarding declined as with the accepted. We need to change the logic and update how this endpoint works.

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +  Users.findOne({username: req.session.username}, (err, foundUser) => {
we don't have `session`. you should can access authenticated user via body, `req.body.user.id` to get their id for instance.

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +  let pendingEvents = []
this controller should find all the `pendingEvents` ids for the user and then fetch them from the `Event` collection

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +const getAllUserEvents = async (req, res) => {
this should get all `acceptedEvents` of the user and then fetch them from `Event` collection

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +    Users.findOne({username: req.session.username}, (err, foundUser) => {
once again, `req.session.username` does not exist.

2021-11-14 16:49 UTC, nedjulius commented on back-end/controllers/events.js
> +//const {EVENTS: fakeEventsData} = require('../mock-data/events');
remove commented out code. why should we leave it?

2021-11-14 18:09 UTC, fm1539 commented on back-end/controllers/events.js
> +          Events.findOne({id: req.body.eventId}, (err, foundEvent) => {
so even if I imported them as plurals names, I still have to remove the "s"?

2021-11-14 18:10 UTC, fm1539 commented on back-end/controllers/events.js
> +          Events.findOne({id: req.body.eventId}, (err, foundEvent) => {
When i ran npm run lint, this error didnt seem to be detected.

2021-11-14 18:20 UTC, fm1539 commented on back-end/controllers/events.js
> +  let pendingEvents = []
don't I do that though? I search user collection based on username, then for each event in the user's events array, i query the events schema to see if its pending and if it is I add it to the array to send as response

2021-11-14 18:22 UTC, fm1539 commented on back-end/controllers/events.js
> +const acceptPending = (req, res) => { //assuming events array in user schema contains both pending and accepted
I agree with this, should I change my querying then based on this new model or wait until the schema is updated?

2021-11-15 02:14 UTC, nedjulius commented on back-end/controllers/events.js
> +          Events.findOne({id: req.body.eventId}, (err, foundEvent) => {
The way you import it is incorrect, the imports are not named. In order for it to work you should import it like this `const Events = require('../models/Event')` but I would keep it singular because we are working on a specific model.

2021-11-15 02:15 UTC, nedjulius commented on back-end/controllers/events.js
> +  let pendingEvents = []
I am talking about the updated logic, when the user schema will have a `pendingEvents` field

2021-11-15 18:17 UTC, nedjulius commented on back-end/controllers/events.js
> +const acceptPending = (req, res) => { //assuming events array in user schema contains both pending and accepted
It's updated.

2021-11-17 01:08 UTC, nedjulius commented on back-end/controllers/events.js
> +        if (foundUser.events[i] == req.body.eventId) {
you could simplify this with `.filter` method: `foundUser.pendingEvents.filter((pendingEvent) => pendingEvent.id !== req.body.eventId)`

2021-11-17 01:15 UTC, nedjulius commented on back-end/controllers/events.js
> +  User.findOne({username: req.body.user.id}, (err, foundUser) => {
I think a more imperative way to do this would be with `await` expressions. also, you need to return the actual `Events`, not only their ids:

```
try {
  const user = await User.findById(req.body.user.id);
  const events = await Event.find({ '_id': { $in: user.pendingEvents } });
  res.status(200).json(events);
} catch (e) {
  console.error(e)
}
```

2021-11-18 18:37 UTC, nedjulius reviewed
`events.test.js` is failing now. would you be able to fix the test cases?

2021-11-18 21:57 UTC, mnu213 reviewed
I saw julius suggested using an imperative style for getPendingEvents, i'm wondering is this impossible to do with declinePending since its post? Or is it just less required since there is only one "find".

2021-11-23 21:46 UTC, nedjulius approved these changes

2021-11-23 21:46 UTC, merged