Landing page
software-students-fall2021/project-setup-eventedge pull request #176
Opened 2021-11-30 06:36 UTC by ioshir4350

I have improved the UI of the landing page. I have added a video to showcase what the result of using our app can be. In addition, I have organized the description we had before to bullet points. Plus, I have added a feature where the user can provide his or her email to email EventEdge with any questions or concerns. This will be our "free" functionality before registering and logging in.

2021-11-30 17:36 UTC, nedjulius requested changes
some comments. also, you commited `.DS_Store` files to`back-end/controllers`, `back-end`, `back-end/routes/`, `front-end/public` and `front-end/src/components/landing-page` directories. these files are generated by the Mac OS automatically and should not be committed. we should fix the gitignore somehow, but in the meantime, could you remove them please?

2021-11-30 17:36 UTC, nedjulius commented on back-end/app.js
> +passport.use(jwtStrategy);
you should bring back password initialization and strategy usage at the top, as it was before, and move the email routes to the bottom. why did you change it?

2021-11-30 17:36 UTC, nedjulius commented on front-end/src/components/footer/footer.module.css
> +  /* position: absolute; */
remove this commented out code pls

2021-11-30 17:36 UTC, nedjulius commented on front-end/src/components/landing-page/landing-page.module.css
> +  /* margin-top: -21px; */
remove commented-out code

2021-11-30 17:36 UTC, nedjulius commented on front-end/src/components/landing-page/landing-page.module.css
> +  /* position: relative; */
remove commented-out code

2021-11-30 17:36 UTC, nedjulius commented on back-end/controllers/email.js
> +      pass: process.env.EMAILPASSWORD
with env variables, the usual convention is to use `UPPER_CASE`. I'd suggest you to change it to `EMAIL_PASSWORD`

2021-11-30 17:36 UTC, nedjulius commented on back-end/controllers/email.js
> +  transporter.sendMail(mailOptions, function (err, info) {
I would rewrite this whole block with `await/async` syntax. the callback syntax is just ugly and hard to read. it would look something like this:
```
try {
  const info = await transporter.sendMail(mailOptions);
  console.log('Email sent: ' + info.response);
  return res.status(200).json(mailOptions);
} catch (e) {
  console.log(e)
  return res.status(400).json({error: 'Email is not able to send'});
}
```

2021-11-30 21:57 UTC, ioshir4350 commented on back-end/app.js
> +passport.use(jwtStrategy);
I thought since we don't use jwt authentication for landing page, we could include email before it. It isn't a private route. I can place it down, if that's not how "use" operates.

2021-11-30 22:06 UTC, ioshir4350 commented on back-end/app.js
> +passport.use(jwtStrategy);
Update: I misunderstood. I have changed it back to what it was before. Will be doing another push soon

2021-11-30 22:16 UTC, ioshir4350 commented
I have made the requested changes and deleted the .DS_Store files from the branch. @nedjulius

2021-12-01 01:06 UTC, nedjulius commented on front-end/src/components/landing-page/landing-page.jsx
>      <>
you can also delete this fragment, because you already have a div wrapper that wraps the whole component.

2021-12-01 01:07 UTC, nedjulius commented on front-end/src/components/landing-page/landing-page.jsx
> +      <div style={{height: '100%'}}>
could add a style to the landing-page.module.css with this property? it is a good practice to not have inline styles

2021-12-01 01:20 UTC, nedjulius approved these changes

2021-12-01 01:21 UTC, merged